# No one in bedroom
- alias: No one in bedroom
  trigger:
    entity_id: binary_sensor.bedroom_motion
    platform: state
    to: 'off'
    from: 'on'
    for: 
      hours: "00"
      minutes: "30"
      seconds: "00"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '10:00:00'
        before: '21:00:00'
      - condition: state
        entity_id: input_boolean.bedroom_presence_check
        state: 'on'
      - condition: state
        state: 'on'
        entity_id: binary_sensor.workday

  action:
    - service: python_script.notify
      data:
        message: "Looks like no one is in bedroom, switching off everyting in bedroom"
        text: 1
    - service: homeassistant.turn_on
      data:
        entity_id: script.shutdown_bedroom
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.bedroom_presence_check
############################################################################
- alias: someone in bedroom
  trigger:
    entity_id: binary_sensor.bedroom_motion
    platform: state
    to: 'on'
   # from: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.bedroom_presence_check
    - service: image_processing.scan
      entity_id: image_processing.deepstack_od_bedroom
    - service: image_processing.scan
      entity_id: image_processing.deepstack_fd_bedroom
    - service: image_processing.scan
      entity_id: image_processing.facebox_bedroom
    - service: image_processing.scan
      entity_id: image_processing.rekognition_bedroom
############################################################################
- alias: turn on bathroom light on motion
  trigger:
    entity_id: binary_sensor.bathroom_motion
    platform: state
    to: 'on'
    from: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.bathroom_light
############################################################################
- alias: turn off bathroom light if no motion
  trigger:
    entity_id: binary_sensor.bathroom_motion
    platform: state
    to: 'off'
    for:
      hours: "00"
      minutes: "05"
      seconds: "00"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.bathroom_light