# Turn off everyting in familyroom every 15 min as motion is not working
- alias: shutdown familyroom every 15 min
  initial_state: false
  trigger:
    platform: time_pattern
    minutes: '/15'
  action:
    # - service: python_script.notify
    #   data:
    #     message: "Looks like no one is in familyroom, switching off everyting in familyroom"
    #     text: 1
    - service: homeassistant.turn_on
      data:
        entity_id: script.shutdown_familyroom
########################################################################################################    
# No one in familyroom
- alias: No one in familyroom
  initial_state: true
  trigger:
    entity_id: binary_sensor.familyroom_motion
    platform: state
    to: 'off'
    from: 'on'
    for: 
      minutes: 15
  condition:
     - condition: state
       entity_id: input_boolean.familyroom_presence_check
       state: 'on'
  action:
    - service: python_script.notify
      data:
        message: "Looks like no one is in familyroom, switching off everyting in familyroom"
        announce: 1
        room: home
        override: 1
    - service: homeassistant.turn_on
      data:
        entity_id: script.shutdown_familyroom
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.familyroom_presence_check
############################################################################
- alias: someone in familyroom
  initial_state: true
  trigger:
    entity_id: binary_sensor.familyroom_motion
    platform: state
    to: 'on'
    from: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.familyroom_presence_check
############################################################################
- alias: turn on family bathroom light on motion
  initial_state: true
  trigger:
    entity_id: binary_sensor.family_bathroom_motion
    platform: state
    to: 'on'
    from: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.family_bathroom_light
############################################################################
- alias: turn off family bathroom light if no motion
  initial_state: true
  trigger:
    - entity_id: binary_sensor.family_bathroom_motion
      platform: state
      to: 'off'
      for:
        minutes: 15
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.family_bathroom_light

########################################################################################################    
# Iron on for more than 15 minutes
- alias: Iron on for more than 15 minutes
  initial_state: true
  trigger:
    entity_id: switch.sonoff_iron
    platform: state
    to: 'on'
    from: 'off'
    for: 
      hours: "00"
      minutes: "15"
      seconds: "00"
  action:
    - service: rest_command.assistant_broadcast
      data:
        command: "Looks like iron is left on for last 15 minutes, don't you guys care of it? I'm switching off now!!"
    - service: homeassistant.turn_off
      data:
        entity_id: switch.sonoff_iron
