# reached office
- alias: Jyoti Reached Office
  initial_state: true      
  action:
    data:
      message: Jyoti has reached office now
    service: python_script.notify
  trigger:
    entity_id: device_tracker.jyoti
    event: enter
    platform: zone
    zone: zone.UBS

# left office
- alias: Jyoti Left Office
  initial_state: true    
  action:
    data:
      message: Jyoti has left office now
    service: python_script.notify
  trigger:
    entity_id: device_tracker.jyoti
    event: leave
    platform: zone
    zone: zone.UBS

# reached home
- alias: Jyoti Reached home
  initial_state: true    
  action:
    - service: python_script.notify
      data:
        message: Jyoti has reached home now
    - service: input_boolean.turn_on
      entity_id: input_boolean.jyoti_at_home
  condition:
    - condition: state
      state: 'off'
      entity_id: input_boolean.jyoti_at_home      
  trigger:
    entity_id: device_tracker.jyoti
    event: enter
    platform: zone
    zone: zone.home

# left home
- alias: Jyoti Left home
  initial_state: true    
  action:
    - service: python_script.notify
      data:
        message: Jyoti has left home now
    - service: input_boolean.turn_off
      entity_id: input_boolean.jyoti_at_home
    - service: python_script.set_state
      data:
        entity_id: sensor.jyoti_room_location
        state: "Not at home"      
  condition:
    - condition: state
      entity_id: device_tracker.jyoti_nmap
      state: 'not_home'
  trigger:
    entity_id: device_tracker.jyoti
    event: leave
    platform: zone
    zone: zone.home

#travelling
- alias: Jyoti is travelling
  initial_state: true    
  trigger:
    platform: event
    event_type: places_state_update
  condition:
    - condition: template
      value_template: '{{ trigger.event.data.entity == "jyoti" }}'
    - condition: template
      value_template: '{{ trigger.event.data.devicetracker_zone != "home" }}'
    - condition: state
      state: 'off'
      entity_id: input_boolean.jyoti_at_home
  action:
  - service: python_script.notify
    data_template:
      message: '{{trigger.event.data.entity}} has reached {{trigger.event.data.formatted_address}}'
