############################################################################
- alias: someone in kitchen based on sun events
  initial_state: false
  trigger:
    entity_id: binary_sensor.kitchen_motion
    platform: state
    to: 'on'
    #from: 'off'
  condition:
    - condition: state
      entity_id: light.kitchen_light
      state: 'off'
    - condition: sun
      after: sunset
      after_offset: '-01:00:00'
      before: sunrise
      before_offset: '+03:00:00'
  action:
    - service: light.turn_on
      entity_id: light.kitchen_light
########
- alias: someone in kitchen based on sunlight
  initial_state: true
  trigger:
    entity_id: binary_sensor.kitchen_motion
    platform: state
    to: 'on'
  condition:
    - condition: state
      entity_id: light.kitchen_light
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.sunlight
      #above: 0
      below: 500
  action:
    - service: light.turn_on
      entity_id: light.kitchen_light
##############################################################################

###############
- alias: No one in kitchen 
  trigger:
    platform: template
    value_template: > 
      {% set no_motion_since=states.binary_sensor.kitchen_motion.attributes['No motion since'] | int %}
      {% set current_state=states.binary_sensor.kitchen_motion.state %}
      {{ (is_state("binary_sensor.morning","on") and current_state=="off" and no_motion_since > 60 * 5) or
         (is_state("binary_sensor.evening","on") and current_state=="off" and no_motion_since > 60 * 15) or
         (is_state("binary_sensor.night","on") and current_state=="off" and no_motion_since > 60 * 2) or 
         (is_state("binary_sensor.morning","off") and 
          is_state("binary_sensor.morning","off") and
          is_state("binary_sensor.morning","off") and 
          current_state=="off" and 
          no_motion_since > 60 * 5
          )
      }}
  action:
    - service: python_script.notify
      data_template:
        message: "Looks like no one is in kitchen since {{states.binary_sensor.kitchen_motion.attributes['No motion since'] | int/60 |float}} minutes, switching off lights"
        text: 1
    - service: light.turn_off
      entity_id: light.kitchen_light

