# No one in livingroom
- alias: No one in livingroom
  trigger:
    entity_id: binary_sensor.livingroom_motion
    platform: state
    to: 'off'
    from: 'on'
    for: 
      hours: "00"
      minutes: "60"
      seconds: "00"
  condition:
    - condition: state
      entity_id: input_boolean.livingroom_presence_check
      state: 'on'
    - condition: state 
      entity_id: binary_sensor.workday
      state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.shutdown_livingroom
############################################################################
- alias: someone in livingroom turn on presense check
  trigger:
    entity_id: binary_sensor.livingroom_motion
    platform: state
    to: 'on'
   # from: 'off'
  # condition:
  #   - condition: state
  #     entity_id: input_boolean.livingroom_presence_check
  #     state: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.livingroom_presence_check
    # - service: image_processing.scan
    #   entity_id: image_processing.deepstack_od_livingroom
    # - service: image_processing.scan
    #   entity_id: image_processing.deepstack_fd_livingroom
    - service: image_processing.scan
      entity_id: image_processing.facebox_livingroom
    - service: image_processing.scan
      entity_id: image_processing.rekognition_livingroom 
###############################################################################
- alias: someone in livingroom switch on fan if ac is not on
  trigger:
    entity_id: binary_sensor.livingroom_motion
    platform: state
    to: 'on'
    from: 'off'
  condition:
    - condition: state
      entity_id: switch.livingroom_aircon
      state: 'off'
    - condition: state
      entity_id: fan.livingroom_fan
      state: 'off'  
  action:
    - service: fan.turn_on
      data:
        entity_id: fan.livingroom_fan
        speed: 'medium'

############################################################################
- alias: tv is turned off
  initial_state: true
  trigger:
    entity_id: binary_sensor.livingroom_tv
    platform: state
    to: 'off'
    from: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.livingroom_aircon_off
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.livingroom_tv_state
############################################################################
- alias: tv is turned on
  initial_state: true
  trigger:
    entity_id: binary_sensor.livingroom_tv
    platform: state
    to: 'on'
    from: 'off'
  condition:
    - condition: state
      state: 'home'
      entity_id: device_tracker.lalit
    - condition: state
      state: 'off'
      entity_id: input_boolean.livingroom_tv_state
  action:
    # - service: script.turn_on
    #   data:
    #     entity_id: script.livingroom_aircon_on
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.livingroom_tv_state
#######################################################################################
# sleep time check 
- alias: sleep time check
  trigger:
    platform: time_pattern
    hours: '/2'    
  condition:
    - condition: state  
      entity_id: binary_sensor.sleep_mode
      state: 'on'  
    - condition: state
      entity_id: input_boolean.livingroom_presence_check
      state: 'off'
  action:
    - service: script.turn_on
      data:
        entity_id: script.shutdown_livingroom
###########################################################################################
- alias: main door is closed
  initial_state: true
  trigger:
    entity_id: binary_sensor.main_door
    platform: state
    to: 'off'
    from: 'on'
  condition:
    - condition: time
      before: '21:00:00'
      after: '18:00:00'
  action:
    - service: python_script.notify
      data_template:
        message: 'krpya dhayan de! Joote-chappal almaari mein rakhen, shaam ko safai ke liye shaanta-bai aaegee'
        announce: 1
###########################################################################################
- alias: main door is opened 
  initial_state: true
  trigger:
    entity_id: binary_sensor.main_door
    platform: state
    to: 'on'
    from: 'off'
  condition:
    - condition: time
      before: '21:00:00'
      after: '18:00:00'
  action:
    - service: script.turn_on
      entity_id: script.play_door_chimes
