# No one in office
- alias: No one in office
  trigger:
    entity_id: binary_sensor.office_motion
    platform: state
    to: 'off'
    from: 'on'
    for: 
      hours: "00"
      minutes: "30"
      seconds: "00"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '10:00:00'
        before: '21:00:00'
      - condition: state
        entity_id: input_boolean.office_presence_check
        state: 'on'
      - condition: state
        state: 'on'
        entity_id: binary_sensor.workday
  action:
    - service: python_script.notify
      data:
        message: "Looks like no one is in office, switching off everyting in office"
        text: 1
    - service: homeassistant.turn_on
      data:
        entity_id: script.shutdown_office
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.office_presence_check
############################################################################
- alias: someone in office
  trigger:
    entity_id: binary_sensor.office_motion
    platform: state
    to: 'on'
    #from: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: input_boolean.office_presence_check
    - condition: numeric_state
      entity_id: sensor.sunlight
      #above: 0
      below: 500
    - condition: state
      entity_id: light.office_light
      state: 'off'
    - condition: time
      before: '22:00:00'
      after: '07:00:00' 
    - service: light.turn_on
      entity_id: light.office_light

############################################################################
- alias: turn off ac at morning
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.morning_alarm_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
    - service: climate.turn_off
      entity_id: climate.bedroom_aircon
