homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: Asia/Singapore
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  #packages: !include_dir_merge_named packages
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - ::1
      allow_bypass_login: true
auth:
frontend: 
  themes: !include_dir_merge_named themes
config:
default_config:
system_log:
  fire_event: true
logger:
  default: info
  logs:
    custom_components.places.sensor: error
    homeassistant.components.proximity: error

updater:
discovery:
conversation:
  intents:
    ShoppingListAddItem:
      - Add {item} to my shopping list
history:
logbook:
recorder:
#map:
sun:
http: !include http.yaml
notify: !include notify.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
tts: !include tts.yaml
fan: !include fan.yaml
ifttt: !include ifttt.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
input_number: !include input_numbers.yaml
input_datetime: !include input_datetime.yaml
switch: !include switches.yaml
light: !include lights.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
device_tracker: !include device_trackers.yaml
zone: !include zones.yaml
proximity: !include proximity.yaml
media_player: !include media_players.yaml
google_assistant: !include google_assistant.yaml
dialogflow: 
intent_script: !include intent_scripts.yaml
shopping_list:
cloud: 
python_script:
media_extractor:
  default_query: worst
  customize:
    media_player.office:
      video: bestvideo
      music: bestaudio[ext=m4a]/bestaudio[ext=ogg]/bestaudio

input_text: !include input_text.yaml
# google:
#   client_id: !secret google_calendar_client_id
#   client_secret: !secret google_calendar_client_secret

climate: !include climate.yaml
camera: !include camera.yaml
vacuum: !include vacuum.yaml
remote: !include remote.yaml
lovelace: 
  mode: storage
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
  
system_health:
smartir:
  update_branch: rc
hacs:
  token: !secret my_github_access_token

image_processing: !include image_processing.yaml

variable:
  base_url_full: 
    value: !secret base_url_full

timer:
  bedroom_shutdown_reminder:
    duration: '00:30:00'

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  reload: always

rest_command:
  assistant_broadcast:
    url: !secret assistant_relay_url
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "broadcast":true}'
  assistant_converse:
    url: !secret assistant_relay_url
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "converse":true}'
  assistant_relay:
    url: !secret assistant_relay_url
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"username"}'
  assistant_preset:
    url: !secret assistant_relay_url
    method: POST
    content_type: 'application/json'
    payload: '{"preset":"{{ preset }}"}'

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc 
  sp_key: !secret sp_key



