homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: Asia/Singapore
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      #   - 127.0.0.1
      #   - ::1        
      # #allow_bypass_login: true
    
auth:
frontend: !include frontend.yaml
config:
default_config:
#breaking_changes:
system_log:
  fire_event: true
logger:
  default: info
  logs:
    custom_components.device_tracker.composite: error
    custom_components.places.sensor: error
    homeassistant.components.media_player.spotify: debug
    homeassistant.components.proximity: error
    #homeassistant.components.ifttt: debug
    #homeassistant.components.automation: debug
    homeassistant.components.mqtt: error
    googleapiclient.discovery: error
    homeassistant.components.image_processing: error

updater:
discovery:
  ignore:
    - plex_mediaserver
    - samsung_tv
    - yeelight
conversation:
  intents:
    ShoppingListAddItem:
      - Add {item} to my shopping list
history:
logbook:
recorder:
map:
sun:
http: !include http.yaml
notify: !include notify.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
tts: !include tts.yaml
fan: !include fan.yaml
ifttt: !include ifttt.yaml
input_boolean: !include input_booleans.yaml
input_select: !include input_selects.yaml
input_number: !include input_numbers.yaml
input_datetime: !include input_datetime.yaml
switch: !include switches.yaml
light: !include lights.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
device_tracker: !include device_trackers.yaml
zone: !include zones.yaml
proximity: !include proximity.yaml
media_player: !include media_players.yaml
google_assistant: !include google_assistant.yaml
dialogflow: 
intent_script: !include intent_scripts.yaml
shopping_list:
cloud: !include cloud.yaml
python_script:
media_extractor:
  default_query: worst
  customize:
    media_player.office:
      video: bestvideo
      music: bestaudio[ext=m4a]/bestaudio[ext=ogg]/bestaudio
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_gateway_key
input_text: !include input_text.yaml
# mqtt:
#   broker: !secret mqtt_broker
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   keepalive: 60
#   port: 1883
#   client_id: hass
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

climate: !include climate.yaml
camera: !include camera.yaml
vacuum: !include vacuum.yaml
remote: !include remote.yaml
#gpslogger:
lovelace: 
  mode: yaml
# weather:
#   - platform: darksky
#     api_key: !secret darksky_api_key
custom_updater:
  hide_sensor: false
  show_installable: false
  track:
    - components
    - cards
    - python_script
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
    - https://raw.githubusercontent.com/benct/lovelace-multiple-entity-row/master/tracker.json

yeelight:
  devices:
    192.168.1.130:
      name: bedroom mini lamp
      
system_health:
smartir:
  update_branch: rc

# hacs:
#   token: !secret my_github_access_token


image_processing:
  - platform: deepstack_object
    ip_address: localhost
    port: 5001
    scan_interval: 20000
    save_file_folder: '/config/www/deepstack_person_images'
    target: person
    confidence: 50
    source:
      - entity_id: camera.livingroom
        name: deepstack_od_livingroom
      - entity_id: camera.bedroom
        name: deepstack_od_bedroom

  - platform: deepstack_face
    ip_address: localhost
    port: 5001
    scan_interval: 20000
    #save_file_folder: '/config/www/deepstack_person_images'
    #target: person
    confidence: 50
    source:
      - entity_id: camera.livingroom
        name: deepstack_fd_livingroom
      - entity_id: camera.bedroom
        name: deepstack_fd_bedroom

  - platform: facebox
    ip_address: localhost
    port: 8090
    source:
      - entity_id: camera.livingroom
        name: facebox_livingroom
      - entity_id: camera.bedroom
        name: facebox_bedroom

  - platform: amazon_rekognition
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    #region_name: eu-west-1 # optional region, default us-east-1
    #target: Car # Optional target object, default Person
    source:
      - entity_id: camera.livingroom
        name: rekognition_livingroom
      - entity_id: camera.bedroom
        name: rekognition_bedroom

twilio:
  account_sid: !secret twilio_account_sid 
  auth_token: !secret twilio_auth_token
  