#########################################################################
# Geographic
#
#  Anything to do with zones, travel, etc.
#########################################################################

homeassistant:
  customize:
    proximity.home:
      friendly_name: Anyone's proximity
    proximity.her_home:
      friendly_name: Her proximity
    proximity.his_home:
      friendly_name: His proximity
    # sensor.org_operating_status:
      # friendly_name: !secret org_operating_status_name
      # icon: mdi:briefcase-check
    # sensor.org_operating_status_message:
      # friendly_name: !secret org_operating_status_desc_name
      # icon: mdi:briefcase-check
  customize_glob:
    'sensor.*_commute':
      icon: mdi:car

# Group geo-related entities.
group:
  Geo:
    - sensor.his_morning_commute
    - sensor.his_evening_commute
    - sensor.her_morning_commute
    - sensor.her_evening_commute
    - sensor.her_distance_mean
    - sensor.his_distance_mean
    - proximity.her_home
    - proximity.his_home
    - proximity.home
    - sensor.his_departure_time
    - sensor.her_departure_time
    - sensor.traveling_away
    - sensor.traveling_home
#    - sensor.org_operating_status

zone:
  # Home zone.
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: !secret zone_radius
    icon: mdi:people
  # His work location 1.
  - name: !secret his_work_name_1
    latitude: !secret his_work_latitude_1
    longitude: !secret his_work_longitude_1
    radius: !secret work_zone_radius
  # His work location 2.
  # - name: !secret his_work_name_2
    # latitude: !secret his_work_latitude_2
    # longitude: !secret his_work_longitude_2
    # radius: !secret work_zone_radius
  # Her work location 1.
  - name: !secret her_work_name_1
    latitude: !secret her_work_latitude_1
    longitude: !secret her_work_longitude_1
    radius: !secret work_zone_radius
  # Her work location 2.
  # - name: !secret her_work_name_2
    # latitude: !secret her_work_latitude_2
    # longitude: !secret her_work_longitude_2
    # radius: !secret work_zone_radius
  # Her home (for proximity tracking).
  - name: Her Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: !secret zone_radius
    passive: true
  # His home (for proximity tracking).
  - name: His Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: !secret zone_radius
    passive: true

proximity:
  # Her proximity to home.
  her_home:
    devices:
      - device_tracker.her_phone
    tolerance: 50
    unit_of_measurement: !secret proximity_unit_of_measurement
  # His proximity to home.
  his_home:
    devices:
      - device_tracker.his_phone
    tolerance: 50
    unit_of_measurement: !secret proximity_unit_of_measurement
  # Nearest proximity to home.
  home:
    devices:
      - device_tracker.his_phone
      - device_tracker.her_phone
    tolerance: 50
    unit_of_measurement: !secret proximity_unit_of_measurement

# TBD
binary_sensor:
  - platform: trend
    sensors:
      traveling_home:
        entity_id: proximity.his_home
        device_class: presence
      traveling_away:
        entity_id: proximity.his_home
        device_class: presence
    invert: true
      

sensor:
  # His home departure time.
  - platform: mqtt
    name: "His Departure Time"
    state_topic: "home/departure/his"
  # Her home departure time.
  - platform: mqtt
    name: "Her Departure Time"
    state_topic: "home/departure/her"
  # Organization operating status.
  # - platform: rest
    # scan_interval: 3600
    # resource: !secret org_operating_status
    # method: GET
    # name: org_operating_status
    # value_template: '{{value_json.StatusSummary}}'
  # # Organization operating status message.
  # - platform: rest
    # scan_interval: 3600
    # resource: !secret org_operating_status
    # method: GET
    # name: org_operating_status_message
    # value_template: '{{value_json.ShortStatusMessage}}'
  # Her average distance from home.
  - platform: statistics
    name: Her Distance
    entity_id: proximity.her_home
  # His average distance from home.
  - platform: statistics
    name: His Distance
    entity_id: proximity.his_home
  # Travel time on his morning commute.
  - platform: google_travel_time
    name: His Morning Commute
    api_key: !secret google_travel_time_api_key
    origin: !secret home_address
    destination: !secret his_work_address_1
    options:
      mode: transit
  # Travel time on his evening commute.
  - platform: google_travel_time
    name: His Evening Commute
    api_key: !secret google_travel_time_api_key
    origin: !secret his_work_address_1
    destination: !secret home_address
    options:
      mode: transit
  # Travel time on her morning commute.
  - platform: google_travel_time
    name: Her Morning Commute
    api_key: !secret google_travel_time_api_key
    origin: !secret home_address
    destination: !secret her_work_address_1
    options:
      mode: driving
  # Travel time on her evening commute.
  - platform: google_travel_time
    name: Her Evening Commute
    api_key: !secret google_travel_time_api_key
    origin: !secret her_work_address_1
    destination: !secret home_address
    options:
      mode: driving

automation:
  # Track and record departure time from home for everyone.
  - alias: track departure time
    trigger:
      - platform: state
        entity_id:
          - device_tracker.his_phone
          - device_tracker.her_phone
        from: home
        to: not_home
    action:
      - service: mqtt.publish
        data_template:
          topic: 'home/departure/{{trigger.entity_id.split(".")[1].split("_")[0]}}'
          payload: '{{now().hour}}:{{now().minute}}'
