
###################################################################
input_boolean:
  is_lalit_awake:
    initial: on
    icon: mdi:bedroom
  is_jyoti_awake:
    initial: on
    icon: mdi:bedroom
###################################################################
timer:
  lalit_sleep_confirmation_time:
    duration: '00:15:00'
  jyoti_sleep_confirmation_time:
    duration: '00:15:00'
######################################################################
binary_sensor:
  - platform: mqtt
    state_topic: zanzito/lalit/samsung_pick_up_gesture
    name: lalit_phone_pickup_gesture
    payload_on: ''
sensor:
  - platform: mqtt
    state_topic: "zanzito/lalit/motion_sensor"
    name: lalit_phone_motion_sensor
    value_template: '{{ value_json.value0 | float }}' 
  - platform: mqtt
    state_topic: "zanzito/lalit/screen_orientation_sensor"
    name: lalit_phone_screen_orientation_sensor
    value_template: '{{ value_json.value0 |float }}'

  - platform: template
    sensors:
      lalit_phone_last_pickup_gesture_timestamp:
      value_template: '{{1==1}}'

###################################################################
automation:
###################################################################
# lalit - mark as sleeping at 11pm by default
  - alias: lalit - mark as sleeping by default
    trigger: 
      - platform: time
        at: '23:00:00'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.is_lalit_awake

# lalit - as awake on gesture
  - alias: lalit - start timer and mark awake on pick up gesture
    trigger:
      platform: mqtt
      topic: zanzito/lalit/samsung_pick_up_gesture
    action:
      # - service: python_script.notify
      #   data:
      #     message: "lalit gesture received"
      #     text: 1
      #     tell: lalit
      - service: input_boolean.turn_on
        entity_id: input_boolean.is_lalit_awake
      - service: timer.cancel
        data:
          entity_id: timer.lalit_sleep_confirmation_time
      - service: timer.start
        data:
          entity_id: timer.lalit_sleep_confirmation_time
          duration: '00:15:00'
#lalit - sleep time confirmation started
  - alias: lalit - sleep time confirmation started
    trigger: 
      platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.lalit_sleep_confirmation_time
    action:
      # - service: python_script.notify
      #   data:
      #     message: "lalit sleep time confirmation started"
      #     text: 1
      #     tell: lalit  
# lalit - gesture is not receveid before timer has finished
  - alias: lalit - gesture is not receveid before timer has finished
    trigger:
      platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.lalit_sleep_confirmation_time
    condition:
      - condition: state
        state: 'on'
        entity_id: input_boolean.is_lalit_awake
    action:
      # - service: python_script.notify
      #   data:
      #     message: "lalit gesture not received and timer ended"
      #     text: 1
      #     tell: lalit
      - service: input_boolean.turn_off
        entity_id: input_boolean.is_lalit_awake

       