
homeassistant:
  customize:
    script.spotify_music:
      friendly_name: 'Play'
      icon: mdi:play

group:
  music_spotify:
    name: Music 
    entities:
    - input_select.spotify_playlist
    - input_select.spotify_source
    - script.spotify_music
    - input_number.spotify_volume

script:
  spotify_music:
    alias: Play selected spotify playlist
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.spotify
          volume_level: '0.40'
      -  service: media_player.select_source
         data_template: 
           entity_id: media_player.spotify
           source: >
            {% if is_state("input_select.spotify_source", "SP3") %} SP3
            {% elif is_state("input_select.spotify_source", "Office speaker") %} Office speaker
            {% endif %}
      -  service: media_player.play_media
         data_template:
           entity_id: media_player.spotify
           media_content_type: playlist
           media_content_id: >
            {% if is_state("input_select.spotify_playlist", "Morning Alarm") %} spotify:user:spotify:playlist:37i9dQZF1DX4PP3DA4J0N8
            {% elif is_state("input_select.spotify_playlist", "Bali Chill-Out") %} spotify:user:spotify:playlist:37i9dQZF1DXbKpCeB6bby3
            {% endif %}

automation:
  - alias: 'Set Spotify Volume'
    trigger:
      platform: state
      entity_id: input_slider.spotify_volume
    action:
      service: media_player.volume_set
      data_template:
        entity_id: media_player.spotify
        volume_level: '{{  states.input_number.spotify_volume.state  }}'


input_number:
  spotify_volume:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
input_select:
  spotify_playlist:
    name: 'Playlist:'
    options:
      - Morning Alarm
      - Bali Chill-Out
    icon: mdi:spotify
  spotify_source:
    name: 'Source:'
    options:
      - SP3
      - Office speaker
    initial: Office speaker
    icon: mdi:speaker-wireless

