- alias: "Medicine reminder for after lunch" 
  trigger:
    - platform: time
      at: '14:00:00'
    - platform: time_pattern
      minutes: '/15'
      seconds: '00'
  condition:
    condition: state
    entity_id: input_boolen.medicine_reminder_flag  
    state: 'off'
  action:
    service: notify.html5
    data:
      message: "Did you take your medicine after lunch?"
      data:
        actions:
          - action: "medicine_takenYes"
            title: "Yes, I've taken"
          - action: "medicine_takenNo"
            title: "No, not yet"

##Medicine taken Yes ########################################################
- alias: Medicine taken
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: medicine_takenYes
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.medicine_reminder_flag
    - service: notify.html5
      data_template:
        message: "Thank you for taking medicine on time, well done!"
        

#Medicine taken No ########################################################
- alias: Medicine not taken
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: medicine_takenNo
  action:
    - service: notify.html5
      data_template:
        message: "Ok will remind you in next 15 minutes"
        title: "Medicine not taken yet"
          